### ISSUE TITLE
Reset value of DMCONTROL.hartstatus

### ISSUE THREAD

**Issue by mwachs5** [sifive/riscv-debug-spec#29]
The reset value of DMCONTROL.hartstatus is '-'. What does that mean exactly, just "unknown, but meaningful"? Or does it not become valid until we start writing to CONTROL register?

**Comment by timsifive** [comment]
It doesn't have a real reset value, since the bit always reflects the current state of the currently selected hart. Typically the hart will be running after reset, but if it's not then hartstatus should reflect that.

**Comment by mwachs5** [comment]
Ok.
