### ISSUE TITLE
Match Control table runs off the bottom of the page

### ISSUE THREAD

**Issue by mwachs5** [sifive/riscv-debug-spec#3]
Match Control 9.1.5, the "action" field is too long and I can't read the bottom

**Comment by timsifive** [comment]
The table uses xtab's xtabular environment for this reason, but it doesn't seem to work for every table.

**Comment by mwachs5** [comment]
Maybe we can force a break before "action". I can google.

**Comment by mwachs5** [comment]
I couldn't figure out how to fix this in LaTex, but adding another Table in 793bb85 made this problem go away by breaking the table up differently.
