### ISSUE TITLE
Missing advice on when triggers should fire

### ISSUE THREAD

**Issue by asb** [sifive/riscv-debug-spec#37]
The spec currently states:

        Address and data trigger implementation are heavily dependent on how
        the processor core is implemented. To accommodate various
        implementations, load and store address and data triggers may fire at
        whatever point in time is most convenient for the implementation.
        Following the suggestions in the definitions of \Fstore and \Fload will
        lead to the best user experience, however.

However I can't see any such advice around the definition of store and load (https://github.com/sifive/riscv-debug-spec/blob/0.13/hwbp_registers.xml#L182). I think we discussed this issue in a call some time ago, and the consensus was that triggering before the store/load was most useful, especially when considering memory-mapped I/O.

**Comment by mwachs5** [comment]
Added a table for this and referred to it instead of the text about \Fstore, \Fload, in 793bb85
