### ISSUE TITLE
Add Contribution Tips to README

### ISSUE THREAD

**Issue by mwachs5** [sifive/riscv-debug-spec#7]
Should we add instructions for potential contributors to the README?

Also,  if you make commits without a PR, Watchers don't get notified. Should we require PRs for groups of changes, for this reason if nothing else?

**Comment by timsifive** [comment]
I'm happy to accept an improved README.

To get people notified, I think it makes more sense just to post `git log` output to the mailing list every day. At least that seems like less hassle to me.

**Comment by timsifive** [comment]
`git log --since=yesterday.midnight --before=midnight` seems to generate a reasonable list.

**Comment by mwachs5** [comment]
closed by #8
